development:
  sessions:
    default:
      database: asocial
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: asocial
      hosts:
        - localhost:27017