development:
  sessions:
    default:
      database: asocial
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: asocial
      hosts:
        - localhost:27017
        - localhost:27018
        - localhost:27019
  options:
    allow_dynamic_fields: false
    identity_map_enabled: true
    scope_overwrite_exception: true
    skip_version_check: true